class CadastroPage{
  cadastro(nome, sobreNome, email, senha){
      cy.get('#name').type(nome, {log: false})
      cy.get('#lastname').type(sobreNome, {log: false})
      cy.get('#email').type(email, {log: false})
      cy.get('#password').type(senha, {log: false})
      cy.get('.select__indicators > .mr-2').click()
      cy.get('#react-select-2-option-3').click()
      cy.get('.StyledButton__Button-sc-bv92mm-0').click()
      cy.get('#country > .select__control > .select__indicators > .mr-2').click()
      cy.get('#react-select-3-option-0').click()
      cy.get('#state > .select__control > .select__indicators > .mr-2').click({force: true})
      cy.get('#react-select-4-option-4').click()
      cy.get('#city > .select__control > .select__value-container').click()
      cy.get('#react-select-6-option-0').click()
      cy.get('.StyledButton__Button-sc-bv92mm-0').click()
      cy.get('#customLink').type('arquitetura3516')
      cy.contains('.flex-col > .block' , 'Foto')
      cy.get('#inputFile[type="file"]').attachFile('brasil.png')
      .wait(2000)
      cy.get('.StyledButton__Button-sc-bv92mm-0').click()
      cy.get('#level').type('Graduação')
      cy.get('#area').type('Engenharia')
      cy.get('#institution').type('UNIP')
      .wait(2000)
      cy.contains('.jkuPDK' , 'Continuar')
      cy.get('.jkuPDK').click()
      .wait(2000)
      cy.get('#office').click()
      cy.get('#office').type('Engenheiro')
      cy.get('.css-1hwfws3').click()
      cy.get('#react-select-7-option-2').click()
      cy.get('.jkuPDK').click()
      cy.get('.qsifC').click()
      cy.get('#tipo-empreendimento > .select__control > .select__value-container').click()
      cy.get('#react-select-8-option-2').click()
      cy.get(':nth-child(2) > :nth-child(1) > #autocomplete > .css-s92srz-control > .css-1hwfws3').click()
      cy.get('#react-select-9-option-2').click()
      cy.get(':nth-child(3) > :nth-child(1) > #autocomplete > .css-s92srz-control > .css-1hwfws3').should('be.visible').type('LCS{enter}')
      cy.get('#country > .select__control > .select__indicators > .mr-2').click()
      cy.get('#react-select-23-option-0').click()
      cy.get('#state > .select__control > .select__indicators > .mr-2').click()
      cy.get('#react-select-24-option-7').click()
      cy.get('#city > .select__control > .select__indicators > .mr-2').click()
      cy.get('#react-select-25-option-10').click()
      cy.get('#coverImageOption > .select__control > .select__indicators > .mr-2').click()
      cy.get('#react-select-26-option-1').click()
      cy.get('#inputFile[type="file"]').attachFile('engenheiro.png')
      cy.get('.mb-4 > .cursor-pointer').attachFile(['capa.jpg', 'projeto.jpg', 'engenharia-civil.jpg'], { subjectType: 'drag-n-drop'})
      cy.get('.px-2 > svg').click()
      cy.get('#react-select-27-option-1').click()
      cy.get('#floors').type('2')
      cy.get('#area').type('1000')
      cy.xpath('/html/body/div/div[1]/div[2]/section/div[2]/div/div/form/section/section[4]/div[3]/div[1]/div/div/div[2]/div/div[1]').type('Sienge{enter}')
      cy.xpath('/html/body/div/div[1]/div[2]/section/div[2]/div/div/form/section/section[4]/div[3]/div[2]/div/div/div[2]/div/div[1]').type('PJ{enter}')
      cy.get('#description').type('Casa Nova')
      cy.get('.col-span-2 > .StyledButton__Button-sc-bv92mm-0').click()
      cy.xpath('/html/body/div/div[1]/div[2]/section/div[2]/div/div/form/section/section[5]/div[1]/div/div[2]/div[1]/div/div/div[2]/div/div[1]').type('Lucas Rodrigo{enter}')
      cy.get('#projectFunction-0').type('Analista de projeto',{force: true})
      .wait(2000)
      cy.get(':nth-child(3) > .col-span-1 > .flex > :nth-child(1) > #tags > .css-s92srz-control').click({force: true}).type('LCS Engenharia{enter}')
      cy.get('#avatar-select-17 > .css-s92srz-control > .css-1hwfws3').type('Nenhum{enter}')
      cy.get('.cnepCh').click()
      cy.get('.mt-16 > .w-full > .StyledButton__Button-sc-bv92mm-0').click()
      

    

      
  }
}
export default new CadastroPage 